version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "daily"
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"