export const calendarDefinitions = {
  CalendarEventStatus: {
    type: "string",
    enum: ["scheduled", "completed", "cancelled"],
  },
  CalendarProvider: {
    type: "string",
    enum: ["google", "microsoft"],
  },
  CalendarEventInput: {
    type: "object",
    properties: {
      tutor_id: { type: "string", format: "uuid" },
      animal_id: { type: "string", format: "uuid" },
      interest_id: { type: "string", format: "uuid" },
      title: { type: "string", minLength: 1 },
      description: { type: "string" },
      location: { type: "string" },
      starts_at: { type: "string", format: "date-time" },
      ends_at: { type: "string", format: "date-time" },
      status: { $ref: "#/definitions/CalendarEventStatus" },
      provider: { $ref: "#/definitions/CalendarProvider" },
      external_event_id: { type: "string" },
      external_event_url: { type: "string" },
      metadata: { type: "object", additionalProperties: true },
    },
    required: ["title", "starts_at", "ends_at"],
  },
  CalendarEventPatchInput: {
    type: "object",
    properties: {
      tutor_id: { type: "string", format: "uuid" },
      animal_id: { type: "string", format: "uuid" },
      interest_id: { type: "string", format: "uuid" },
      title: { type: "string", minLength: 1 },
      description: { type: "string" },
      location: { type: "string" },
      starts_at: { type: "string", format: "date-time" },
      ends_at: { type: "string", format: "date-time" },
      status: { $ref: "#/definitions/CalendarEventStatus" },
      provider: { $ref: "#/definitions/CalendarProvider" },
      external_event_id: { type: "string" },
      external_event_url: { type: "string" },
      metadata: { type: "object", additionalProperties: true },
    },
  },
  CalendarEvent: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      tutor_id: { type: "string", format: "uuid" },
      animal_id: { type: "string", format: "uuid" },
      interest_id: { type: "string", format: "uuid" },
      title: { type: "string" },
      description: { type: "string" },
      location: { type: "string" },
      starts_at: { type: "string", format: "date-time" },
      ends_at: { type: "string", format: "date-time" },
      status: { $ref: "#/definitions/CalendarEventStatus" },
      provider: { $ref: "#/definitions/CalendarProvider" },
      external_event_id: { type: "string" },
      external_event_url: { type: "string" },
      metadata: { type: "object", additionalProperties: true },
      created_by: { type: "string", format: "uuid" },
      created_at: { type: "string", format: "date-time" },
      updated_at: { type: "string", format: "date-time" },
      tutor: {
        type: "object",
        properties: {
          id: { type: "string", format: "uuid" },
          name: { type: "string" },
        },
      },
      animal: {
        type: "object",
        properties: {
          id: { type: "string", format: "uuid" },
          name: { type: "string" },
          species: { type: "string" },
        },
      },
    },
    required: ["id", "title", "starts_at", "ends_at", "status"],
  },
  CalendarEventDeleteResponse: {
    type: "object",
    properties: {
      deleted: { type: "boolean" },
      rows: {
        type: "array",
        items: { type: "object", additionalProperties: true },
      },
    },
    required: ["deleted", "rows"],
  },
  CalendarOAuthConnection: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      provider: { $ref: "#/definitions/CalendarProvider" },
      calendar_id: { type: "string" },
      account_email: { type: "string" },
      tenant_id: { type: "string" },
      access_token: { type: "string" },
      refresh_token: { type: "string" },
      token_type: { type: "string" },
      scope: { type: "string" },
      expires_at: { type: "string", format: "date-time" },
      metadata: { type: "object", additionalProperties: true },
      is_active: { type: "boolean" },
      created_by: { type: "string", format: "uuid" },
      updated_by: { type: "string", format: "uuid" },
      created_at: { type: "string", format: "date-time" },
      updated_at: { type: "string", format: "date-time" },
    },
  },
  CalendarOAuthStartResponse: {
    type: "object",
    properties: {
      authorizationUrl: { type: "string" },
      state: { type: "string" },
    },
    required: ["authorizationUrl", "state"],
  },
  CalendarOAuthStatusResponse: {
    type: "object",
    properties: {
      connected: { type: "boolean" },
      connection: { $ref: "#/definitions/CalendarOAuthConnection" },
    },
    required: ["connected"],
  },
};
