-- Combined migrations for ONG Matching Animal.
-- Generated by src/backend/db/scripts/build_combined_migrations.mjs.
-- Includes the baseline schema followed by migrations in filename order.
-- Review before running in production. Run in a clean database or after
-- src/backend/db/scripts/drop_system_tables.sql when you intentionally want a rebuild.
-- ============================================================
-- schema.sql
-- ============================================================
-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Tutors
CREATE TABLE tutors (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  auth_user_id UUID UNIQUE REFERENCES auth.users(id),
  name VARCHAR(120) NOT NULL,
  location geography(POINT),
  custom_fields JSONB DEFAULT '{}'::jsonb,
  onboarding_completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Admin users backed by Supabase Auth
CREATE TABLE admin_users (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR(254) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION is_admin(check_user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM admin_users
    WHERE auth_user_id = check_user_id
      AND is_active = true
  );
$$;

REVOKE ALL ON FUNCTION is_admin(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION is_admin(UUID) TO authenticated;

-- Animals
CREATE TABLE animals (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  owner_id UUID REFERENCES tutors(id),
  name VARCHAR(120) NOT NULL,
  species VARCHAR(64) NOT NULL,
  location geography(POINT),
  custom_fields JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_animals_owner_id
  ON animals (owner_id);

CREATE INDEX idx_animals_location_gist
  ON animals USING gist (location);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'animal-photos',
  'animal-photos',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Animal photos stored in Supabase Storage
CREATE TABLE animal_photos (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  animal_id UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
  bucket_id VARCHAR(63) NOT NULL DEFAULT 'animal-photos',
  storage_path VARCHAR(1024) NOT NULL UNIQUE,
  public_url VARCHAR(2048) NOT NULL,
  content_type VARCHAR(32) NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp', 'image/avif')),
  size_bytes INT NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 5242880),
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX animal_photos_animal_id_idx
  ON animal_photos (animal_id);

CREATE UNIQUE INDEX animal_photos_one_primary_per_animal_idx
  ON animal_photos (animal_id)
  WHERE is_primary;

-- Tutor interest records created when a logged tutor chooses to adopt an animal
CREATE TABLE tutor_interessados (
  tutor_id UUID NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
  animal_id UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
  data_registro TIMESTAMPTZ DEFAULT NOW(),
  uuid_registro UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  CONSTRAINT tutor_interessados_tutor_animal_key UNIQUE (tutor_id, animal_id)
);

CREATE INDEX tutor_interessados_tutor_id_idx
  ON tutor_interessados (tutor_id);

CREATE INDEX tutor_interessados_animal_id_idx
  ON tutor_interessados (animal_id);

-- Calendar events for adoption follow-ups and meetings
CREATE TABLE calendar_events (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  tutor_id UUID REFERENCES tutors(id) ON DELETE SET NULL,
  animal_id UUID REFERENCES animals(id) ON DELETE SET NULL,
  interest_id UUID REFERENCES tutor_interessados(uuid_registro) ON DELETE SET NULL,
  title VARCHAR(160) NOT NULL,
  description TEXT,
  location VARCHAR(255),
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  provider VARCHAR(32) CHECK (provider IN ('google', 'microsoft')),
  external_event_id VARCHAR(255),
  external_event_url VARCHAR(2048),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_by UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CHECK (ends_at > starts_at)
);

CREATE INDEX calendar_events_starts_at_idx
  ON calendar_events (starts_at);

CREATE INDEX calendar_events_tutor_id_idx
  ON calendar_events (tutor_id);

CREATE INDEX calendar_events_animal_id_idx
  ON calendar_events (animal_id);

CREATE UNIQUE INDEX calendar_events_provider_external_idx
  ON calendar_events (provider, external_event_id)
  WHERE provider IS NOT NULL AND external_event_id IS NOT NULL;

-- Public/contact settings for the ONG profile used by adoption flows
CREATE TABLE ong_settings (
  id VARCHAR(32) PRIMARY KEY DEFAULT 'default' CHECK (id = 'default'),
  ong_name VARCHAR(160) NOT NULL DEFAULT 'ONG Matching Animal',
  contact_email VARCHAR(254),
  contact_phone VARCHAR(32),
  whatsapp_phone VARCHAR(32),
  website_url VARCHAR(2048),
  address_line VARCHAR(255),
  city VARCHAR(120),
  state VARCHAR(64),
  postal_code VARCHAR(20),
  social_links JSONB NOT NULL DEFAULT '{}'::jsonb,
  business_hours JSONB NOT NULL DEFAULT '{}'::jsonb,
  adoption_message_template TEXT DEFAULT 'Estou com interesse de adotar {nomeDoAnimal}. O link do interesse e {linkInteresse}.' || E'\n\n' || 'Observacoes:',
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (social_links IS NOT NULL AND jsonb_typeof(social_links) = 'object'),
  CHECK (business_hours IS NOT NULL AND jsonb_typeof(business_hours) = 'object'),
  CHECK (settings IS NOT NULL AND jsonb_typeof(settings) = 'object')
);

INSERT INTO ong_settings (id, ong_name, is_active)
VALUES ('default', 'ONG Matching Animal', true)
ON CONFLICT (id) DO NOTHING;

-- Custom fields catalog used by admin forms and matching rules
CREATE TABLE custom_fields (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  entity_type VARCHAR(16) NOT NULL CHECK (entity_type IN ('tutor', 'animal')),
  field_key VARCHAR(64) NOT NULL CHECK (field_key ~ '^[a-z][a-z0-9_]*$'),
  label VARCHAR(120) NOT NULL,
  field_type VARCHAR(32) NOT NULL DEFAULT 'text' CHECK (field_type IN ('text', 'number', 'boolean', 'select', 'multiselect')),
  options JSONB,
  source_question_id VARCHAR(64),
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (entity_type, field_key)
);

CREATE INDEX custom_fields_entity_active_sort_idx
  ON custom_fields (entity_type, is_active, sort_order, label);

INSERT INTO custom_fields (entity_type, field_key, label, field_type, options, source_question_id, is_active, sort_order) VALUES
  ('tutor', 'pref_energia', 'Energia desejada', 'select', '["baixo","medio","alto"]'::jsonb, 'preferred_energy', true, 10),
  ('tutor', 'tem_criancas', 'Tem crianças', 'boolean', NULL, 'has_children', true, 20),
  ('tutor', 'tamanho_casa', 'Tamanho da casa', 'select', '["apartamento","casa_quintal_pequeno","casa_quintal_grande","pequeno","medio","grande"]'::jsonb, 'home_type', true, 30),
  ('tutor', 'tem_quintal', 'Tem quintal', 'boolean', NULL, NULL, true, 40),
  ('tutor', 'renda_mensal', 'Renda mensal', 'select', '["ate_1000","1000_3000","3000_6000","6000_acima"]'::jsonb, NULL, true, 50),
  ('tutor', 'disponibilidade_tempo', 'Disponibilidade de tempo', 'select', '["meio_periodo","integral"]'::jsonb, 'routine', true, 60),
  ('animal', 'nivel_energia', 'Nível de energia', 'select', '["baixo","medio","alto"]'::jsonb, NULL, true, 10),
  ('animal', 'aceita_criancas', 'Aceita crianças', 'boolean', NULL, NULL, true, 20),
  ('animal', 'espaco_necessario', 'Espaço necessário', 'select', '["apartamento","casa_quintal_pequeno","casa_quintal_grande"]'::jsonb, NULL, true, 30),
  ('animal', 'tamanho', 'Tamanho', 'select', '["pequeno","medio","grande"]'::jsonb, NULL, true, 40),
  ('animal', 'requer_espaco', 'Espaço necessário', 'select', '["apartamento","casa_pequena","casa_grande"]'::jsonb, NULL, true, 50),
  ('animal', 'vacinado', 'Vacinado', 'boolean', NULL, NULL, true, 60);

-- Matching rules
CREATE TABLE matching_rules (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  rule_name VARCHAR(120) NOT NULL,
  tutor_field VARCHAR(64) NOT NULL,
  animal_field VARCHAR(64) NOT NULL,
  comparison_operator VARCHAR(16) DEFAULT '=',
  weight INT DEFAULT 10,
  is_dealbreaker BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE tutor_animal_matches (
  tutor_id UUID NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
  animal_id UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
  compatibility_score INT NOT NULL,
  matched_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  details JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (tutor_id, animal_id)
);

CREATE INDEX idx_tutor_matches_score
  ON tutor_animal_matches (tutor_id, compatibility_score DESC);

CREATE OR REPLACE FUNCTION matching_value_rank(raw_value TEXT)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN raw_value IS NULL THEN 0
    WHEN raw_value ~ '^-?[0-9]+(\.[0-9]+)?$' THEN raw_value::NUMERIC
    WHEN raw_value IN ('baixo', 'apartamento') THEN 1
    WHEN raw_value IN ('medio', 'casa_sem_quintal', 'casa_quintal_pequeno', 'casa_pequena') THEN 2
    WHEN raw_value IN ('alto', 'casa_com_quintal', 'casa_quintal_grande', 'casa_grande') THEN 3
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION compute_tutor_animal_matches(target_tutor_id UUID)
RETURNS TABLE (
  tutor_id UUID,
  animal_id UUID,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  WITH tutor_profile AS (
    SELECT tutors.id, tutors.custom_fields
    FROM tutors
    WHERE tutors.id = target_tutor_id
  ),
  evaluated AS (
    SELECT
      tutor_profile.id AS tutor_id,
      animals.id AS animal_id,
      rules.id AS rule_id,
      rules.rule_name,
      rules.weight,
      rules.is_dealbreaker,
      CASE rules.comparison_operator
        WHEN '=' THEN tutor_profile.custom_fields -> rules.tutor_field = animals.custom_fields -> rules.animal_field
        WHEN '!=' THEN tutor_profile.custom_fields -> rules.tutor_field <> animals.custom_fields -> rules.animal_field
        WHEN 'contains' THEN
          CASE
            WHEN jsonb_typeof(tutor_profile.custom_fields -> rules.tutor_field) = 'array'
              AND jsonb_typeof(animals.custom_fields -> rules.animal_field) = 'array'
              THEN EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(animals.custom_fields -> rules.animal_field) AS animal_item(value)
                WHERE tutor_profile.custom_fields -> rules.tutor_field ? animal_item.value
              )
            WHEN jsonb_typeof(tutor_profile.custom_fields -> rules.tutor_field) = 'array'
              THEN tutor_profile.custom_fields -> rules.tutor_field ? (animals.custom_fields ->> rules.animal_field)
            WHEN jsonb_typeof(animals.custom_fields -> rules.animal_field) = 'array'
              THEN EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(animals.custom_fields -> rules.animal_field) AS animal_item(value)
                WHERE tutor_profile.custom_fields ->> rules.tutor_field ILIKE '%' || animal_item.value || '%'
              )
            ELSE tutor_profile.custom_fields ->> rules.tutor_field ILIKE '%' || (animals.custom_fields ->> rules.animal_field) || '%'
          END
        WHEN '>=' THEN matching_value_rank(tutor_profile.custom_fields ->> rules.tutor_field) >= matching_value_rank(animals.custom_fields ->> rules.animal_field)
        WHEN '<=' THEN matching_value_rank(tutor_profile.custom_fields ->> rules.tutor_field) <= matching_value_rank(animals.custom_fields ->> rules.animal_field)
        ELSE false
      END AS matched
    FROM tutor_profile
    JOIN animals ON true
    CROSS JOIN matching_rules rules
    WHERE rules.is_active = true
      AND tutor_profile.custom_fields ? rules.tutor_field
      AND animals.custom_fields ? rules.animal_field
  ),
  grouped AS (
    SELECT
      evaluated.tutor_id,
      evaluated.animal_id,
      SUM(CASE WHEN evaluated.matched THEN evaluated.weight ELSE 0 END)::INT AS compatibility_score,
      BOOL_OR(evaluated.is_dealbreaker AND NOT evaluated.matched) AS disqualified,
      JSONB_AGG(evaluated.rule_id) FILTER (WHERE evaluated.matched) AS matched_rules,
      JSONB_AGG(JSONB_BUILD_OBJECT(
        'rule_id', evaluated.rule_id,
        'rule_name', evaluated.rule_name,
        'matched', evaluated.matched,
        'weight', evaluated.weight,
        'is_dealbreaker', evaluated.is_dealbreaker
      )) AS details
    FROM evaluated
    GROUP BY evaluated.tutor_id, evaluated.animal_id
  )
  SELECT
    grouped.tutor_id,
    grouped.animal_id,
    grouped.compatibility_score,
    COALESCE(grouped.matched_rules, '[]'::jsonb),
    COALESCE(grouped.details, '[]'::jsonb)
  FROM grouped
  WHERE grouped.disqualified = false
    AND grouped.compatibility_score > 0;
$$;

CREATE OR REPLACE FUNCTION refresh_tutor_animal_matches(target_tutor_id UUID)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  refreshed_rows INT := 0;
BEGIN
  DELETE FROM tutor_animal_matches
  WHERE tutor_id = target_tutor_id;

  INSERT INTO tutor_animal_matches (
    tutor_id,
    animal_id,
    compatibility_score,
    matched_rules,
    details,
    updated_at
  )
  SELECT
    computed.tutor_id,
    computed.animal_id,
    computed.compatibility_score,
    computed.matched_rules,
    computed.details,
    NOW()
  FROM compute_tutor_animal_matches(target_tutor_id) AS computed;

  GET DIAGNOSTICS refreshed_rows = ROW_COUNT;
  RETURN refreshed_rows;
END;
$$;

CREATE OR REPLACE FUNCTION refresh_all_tutor_animal_matches()
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  tutor_record RECORD;
  refreshed_total INT := 0;
BEGIN
  FOR tutor_record IN
    SELECT tutors.id
    FROM tutors
  LOOP
    refreshed_total := refreshed_total + refresh_tutor_animal_matches(tutor_record.id);
  END LOOP;

  RETURN refreshed_total;
END;
$$;

CREATE OR REPLACE FUNCTION match_animals_for_tutor(
  target_tutor_id UUID,
  result_limit INT DEFAULT 10,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  WITH tutor_profile AS (
    SELECT tutors.id, tutors.location
    FROM tutors
    WHERE tutors.id = target_tutor_id
  )
  SELECT
    cache.animal_id,
    animals.name AS animal_name,
    cache.compatibility_score,
    cache.matched_rules,
    cache.details
  FROM tutor_animal_matches AS cache
  JOIN tutor_profile
    ON tutor_profile.id = cache.tutor_id
  JOIN animals
    ON animals.id = cache.animal_id
  WHERE cache.tutor_id = target_tutor_id
    AND (
      max_distance_km IS NULL
      OR tutor_profile.location IS NULL
      OR animals.location IS NULL
      OR ST_DWithin(animals.location, tutor_profile.location, max_distance_km * 1000)
    )
  ORDER BY cache.compatibility_score DESC, animals.name ASC
  LIMIT result_limit;
$$;

CREATE OR REPLACE FUNCTION calculate_match_score(
  target_tutor_id UUID,
  result_limit INT DEFAULT 10,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM match_animals_for_tutor(target_tutor_id, result_limit, max_distance_km);
$$;

CREATE OR REPLACE FUNCTION count_match_candidates_for_tutor(
  target_tutor_id UUID,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS INT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  tutor_location geography(POINT);
  total_candidates INT;
BEGIN
  SELECT location INTO tutor_location
  FROM tutors
  WHERE id = target_tutor_id;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  SELECT COUNT(*)::INT INTO total_candidates
  FROM animals
  WHERE max_distance_km IS NULL
    OR tutor_location IS NULL
    OR animals.location IS NULL
    OR ST_DWithin(animals.location, tutor_location, max_distance_km * 1000);

  RETURN total_candidates;
END;
$$;

-- Dynamic onboarding questions configured by the ONG
CREATE TABLE onboarding_questions (
  id VARCHAR(64) PRIMARY KEY,
  label VARCHAR(180) NOT NULL,
  description TEXT,
  placeholder VARCHAR(255),
  type VARCHAR(32) NOT NULL CHECK (type IN ('text', 'select', 'radio', 'boolean', 'multiselect')),
  options JSONB,
  required BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX onboarding_questions_active_updated_at_idx
  ON onboarding_questions (is_active, updated_at DESC);

INSERT INTO onboarding_questions (id, label, description, placeholder, type, options, required, sort_order) VALUES
  ('home_type', 'Como é a sua moradia?', 'Isso ajuda a recomendar animais compatíveis com o espaço disponível.', NULL, 'radio', '[{"label":"Apartamento","value":"apartamento"},{"label":"Casa sem quintal","value":"casa_sem_quintal"},{"label":"Casa com quintal","value":"casa_com_quintal"}]'::jsonb, true, 10),
  ('routine', 'Quanto tempo você costuma passar em casa?', NULL, 'Selecione sua rotina', 'select', '[{"label":"Poucas horas por dia","value":"poucas_horas"},{"label":"Meio período","value":"meio_periodo"},{"label":"A maior parte do dia","value":"maior_parte_dia"}]'::jsonb, true, 20),
  ('has_children', 'Há crianças na residência?', NULL, NULL, 'boolean', NULL, true, 30),
  ('preferred_energy', 'Qual nível de energia combina com sua rotina?', NULL, NULL, 'radio', '[{"label":"Tranquilo","value":"baixo"},{"label":"Equilibrado","value":"medio"},{"label":"Ativo","value":"alto"}]'::jsonb, true, 40),
  ('preferences', 'O que você procura em um novo companheiro?', 'Escolha uma ou mais opções.', NULL, 'multiselect', '[{"label":"Companhia","value":"companhia"},{"label":"Passeios","value":"passeios"},{"label":"Convívio com outros animais","value":"outros_animais"},{"label":"Perfil independente","value":"independente"}]'::jsonb, true, 50),
  ('notes', 'Quer contar algo importante para a ONG?', NULL, 'Ex.: já tenho um gato adulto em casa', 'text', NULL, false, 60);

ALTER TABLE custom_fields
  ADD CONSTRAINT custom_fields_source_question_id_fkey
  FOREIGN KEY (source_question_id) REFERENCES onboarding_questions(id) ON DELETE SET NULL;

ALTER TABLE tutors ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE animals ENABLE ROW LEVEL SECURITY;
ALTER TABLE animal_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE tutor_interessados ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ong_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE matching_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE tutor_animal_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin users can read their own admin status"
  ON admin_users FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id);

CREATE POLICY "Authenticated users can read active onboarding questions"
  ON onboarding_questions FOR SELECT
  TO authenticated
  USING (is_active = true OR is_admin());

CREATE POLICY "Admins can manage onboarding questions"
  ON onboarding_questions FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Tutors can read their own profile"
  ON tutors FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id);

CREATE POLICY "Tutors can create their own profile"
  ON tutors FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = auth_user_id);

CREATE POLICY "Tutors can update their own profile"
  ON tutors FOR UPDATE
  TO authenticated
  USING (auth.uid() = auth_user_id)
  WITH CHECK (auth.uid() = auth_user_id);

CREATE POLICY "Authenticated users can read animals"
  ON animals FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can create animals"
  ON animals FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update animals"
  ON animals FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Admins can delete animals"
  ON animals FOR DELETE
  TO authenticated
  USING (is_admin());

CREATE POLICY "Authenticated users can read animal photos"
  ON animal_photos FOR SELECT
  TO authenticated
  USING (
    is_admin()
    OR EXISTS (
      SELECT 1
      FROM animals
      WHERE animals.id = animal_photos.animal_id
    )
  );

CREATE POLICY "Admins can create animal photos"
  ON animal_photos FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "Admins can update animal photos"
  ON animal_photos FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Admins can delete animal photos"
  ON animal_photos FOR DELETE
  TO authenticated
  USING (is_admin());

CREATE POLICY "Admins can read interest records"
  ON tutor_interessados FOR SELECT
  TO authenticated
  USING (is_admin());

CREATE POLICY "Tutors can create their own interest records"
  ON tutor_interessados FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM tutors
      WHERE tutors.id = tutor_interessados.tutor_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage calendar events"
  ON calendar_events FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Anyone can read active ONG settings"
  ON ong_settings FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

CREATE POLICY "Admins can manage ONG settings"
  ON ong_settings FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Authenticated users can read active custom fields"
  ON custom_fields FOR SELECT
  TO authenticated
  USING (is_active = true OR is_admin());

CREATE POLICY "Admins can manage custom fields"
  ON custom_fields FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Authenticated users can read active matching rules"
  ON matching_rules FOR SELECT
  TO authenticated
  USING (is_active = true OR is_admin());

CREATE POLICY "Admins can manage matching rules"
  ON matching_rules FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Tutors can read their own cached matches"
  ON tutor_animal_matches FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM tutors
      WHERE tutors.id = tutor_animal_matches.tutor_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can manage cached matches"
  ON tutor_animal_matches FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "Anyone can read animal photo objects"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'animal-photos');

CREATE POLICY "Admins can upload animal photo objects"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'animal-photos'
    AND is_admin()
  );

CREATE POLICY "Admins can update animal photo objects"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'animal-photos'
    AND is_admin()
  )
  WITH CHECK (
    bucket_id = 'animal-photos'
    AND is_admin()
  );

CREATE POLICY "Admins can delete animal photo objects"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'animal-photos'
    AND is_admin()
  );

SELECT refresh_all_tutor_animal_matches();

DO $$
DECLARE
  existing_job_id BIGINT;
BEGIN
  SELECT cron.job.jobid
  INTO existing_job_id
  FROM cron.job
  WHERE cron.job.jobname = 'refresh-tutor-animal-matches'
  LIMIT 1;

  IF existing_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(existing_job_id);
  END IF;

  PERFORM cron.schedule(
    'refresh-tutor-animal-matches',
    '*/15 * * * *',
    $cron$SELECT refresh_all_tutor_animal_matches();$cron$
  );
END;
$$;

-- ============================================================
-- 001_auth_onboarding.sql
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tutors_auth_user_id_key'
  ) THEN
    ALTER TABLE tutors ADD CONSTRAINT tutors_auth_user_id_key UNIQUE (auth_user_id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS onboarding_questions (
  id VARCHAR(64) PRIMARY KEY,
  label VARCHAR(180) NOT NULL,
  description TEXT,
  placeholder VARCHAR(255),
  type VARCHAR(32) NOT NULL CHECK (type IN ('text', 'select', 'radio', 'boolean', 'multiselect')),
  options JSONB,
  required BOOLEAN DEFAULT true,
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO onboarding_questions (id, label, description, placeholder, type, options, required, sort_order) VALUES
  ('home_type', 'Como é a sua moradia?', 'Isso ajuda a recomendar animais compatíveis com o espaço disponível.', NULL, 'radio', '[{"label":"Apartamento","value":"apartamento"},{"label":"Casa sem quintal","value":"casa_sem_quintal"},{"label":"Casa com quintal","value":"casa_com_quintal"}]'::jsonb, true, 10),
  ('routine', 'Quanto tempo você costuma passar em casa?', NULL, 'Selecione sua rotina', 'select', '[{"label":"Poucas horas por dia","value":"poucas_horas"},{"label":"Meio período","value":"meio_periodo"},{"label":"A maior parte do dia","value":"maior_parte_dia"}]'::jsonb, true, 20),
  ('has_children', 'Há crianças na residência?', NULL, NULL, 'boolean', NULL, true, 30),
  ('preferred_energy', 'Qual nível de energia combina com sua rotina?', NULL, NULL, 'radio', '[{"label":"Tranquilo","value":"baixo"},{"label":"Equilibrado","value":"medio"},{"label":"Ativo","value":"alto"}]'::jsonb, true, 40),
  ('preferences', 'O que você procura em um novo companheiro?', 'Escolha uma ou mais opções.', NULL, 'multiselect', '[{"label":"Companhia","value":"companhia"},{"label":"Passeios","value":"passeios"},{"label":"Convívio com outros animais","value":"outros_animais"},{"label":"Perfil independente","value":"independente"}]'::jsonb, true, 50),
  ('notes', 'Quer contar algo importante para a ONG?', NULL, 'Ex.: já tenho um gato adulto em casa', 'text', NULL, false, 60)
ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  placeholder = EXCLUDED.placeholder,
  type = EXCLUDED.type,
  options = EXCLUDED.options,
  required = EXCLUDED.required,
  sort_order = EXCLUDED.sort_order;

ALTER TABLE tutors ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read active onboarding questions" ON onboarding_questions;
CREATE POLICY "Authenticated users can read active onboarding questions"
  ON onboarding_questions FOR SELECT
  TO authenticated
  USING (is_active = true);

DROP POLICY IF EXISTS "Tutors can read their own profile" ON tutors;
CREATE POLICY "Tutors can read their own profile"
  ON tutors FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Tutors can create their own profile" ON tutors;
CREATE POLICY "Tutors can create their own profile"
  ON tutors FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Tutors can update their own profile" ON tutors;
CREATE POLICY "Tutors can update their own profile"
  ON tutors FOR UPDATE
  TO authenticated
  USING (auth.uid() = auth_user_id)
  WITH CHECK (auth.uid() = auth_user_id);

-- ============================================================
-- 002_animal_photos_storage.sql
-- ============================================================
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'animal-photos',
  'animal-photos',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE TABLE IF NOT EXISTS animal_photos (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  animal_id UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
  bucket_id VARCHAR(63) NOT NULL DEFAULT 'animal-photos',
  storage_path VARCHAR(1024) NOT NULL UNIQUE,
  public_url VARCHAR(2048) NOT NULL,
  content_type VARCHAR(32) NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp', 'image/avif')),
  size_bytes INT NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 5242880),
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS animal_photos_animal_id_idx
  ON animal_photos (animal_id);

CREATE UNIQUE INDEX IF NOT EXISTS animal_photos_one_primary_per_animal_idx
  ON animal_photos (animal_id)
  WHERE is_primary;

-- ============================================================
-- 003_admin_users_rls.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_users (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  email VARCHAR(254) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admin_users_auth_user_id_idx
  ON admin_users (auth_user_id)
  WHERE is_active;

CREATE OR REPLACE FUNCTION is_admin(check_user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM admin_users
    WHERE auth_user_id = check_user_id
      AND is_active = true
  );
$$;

REVOKE ALL ON FUNCTION is_admin(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION is_admin(UUID) TO authenticated;

ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tutors ENABLE ROW LEVEL SECURITY;
ALTER TABLE animals ENABLE ROW LEVEL SECURITY;
ALTER TABLE animal_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE matching_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin users can read their own admin status" ON admin_users;
CREATE POLICY "Admin users can read their own admin status"
  ON admin_users FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Admins can read admin users" ON admin_users;

DROP POLICY IF EXISTS "Admins can create admin users" ON admin_users;

DROP POLICY IF EXISTS "Admins can update admin users" ON admin_users;

DROP POLICY IF EXISTS "Admins can delete admin users" ON admin_users;

DROP POLICY IF EXISTS "Authenticated users can read active onboarding questions" ON onboarding_questions;
CREATE POLICY "Authenticated users can read active onboarding questions"
  ON onboarding_questions FOR SELECT
  TO authenticated
  USING (is_active = true OR is_admin());

DROP POLICY IF EXISTS "Admins can manage onboarding questions" ON onboarding_questions;
CREATE POLICY "Admins can manage onboarding questions"
  ON onboarding_questions FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Tutors can read their own profile" ON tutors;
CREATE POLICY "Tutors can read their own profile"
  ON tutors FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id OR is_admin());

DROP POLICY IF EXISTS "Tutors can create their own profile" ON tutors;
CREATE POLICY "Tutors can create their own profile"
  ON tutors FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = auth_user_id OR is_admin());

DROP POLICY IF EXISTS "Tutors can update their own profile" ON tutors;
CREATE POLICY "Tutors can update their own profile"
  ON tutors FOR UPDATE
  TO authenticated
  USING (auth.uid() = auth_user_id OR is_admin())
  WITH CHECK (auth.uid() = auth_user_id OR is_admin());

DROP POLICY IF EXISTS "Admins can delete tutors" ON tutors;
CREATE POLICY "Admins can delete tutors"
  ON tutors FOR DELETE
  TO authenticated
  USING (is_admin());

DROP POLICY IF EXISTS "Authenticated users can read animals" ON animals;
CREATE POLICY "Authenticated users can read animals"
  ON animals FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Tutors can create their own animals" ON animals;
DROP POLICY IF EXISTS "Admins can create animals" ON animals;
CREATE POLICY "Admins can create animals"
  ON animals FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Tutors can update their own animals" ON animals;
DROP POLICY IF EXISTS "Admins can update animals" ON animals;
CREATE POLICY "Admins can update animals"
  ON animals FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Tutors can delete their own animals" ON animals;
DROP POLICY IF EXISTS "Admins can delete animals" ON animals;
CREATE POLICY "Admins can delete animals"
  ON animals FOR DELETE
  TO authenticated
  USING (is_admin());

DROP POLICY IF EXISTS "Authenticated users can read animal photos" ON animal_photos;
CREATE POLICY "Authenticated users can read animal photos"
  ON animal_photos FOR SELECT
  TO authenticated
  USING (
    is_admin()
    OR EXISTS (
      SELECT 1
      FROM animals
      WHERE animals.id = animal_photos.animal_id
    )
  );

DROP POLICY IF EXISTS "Animal owners can create photos" ON animal_photos;
DROP POLICY IF EXISTS "Admins can create animal photos" ON animal_photos;
CREATE POLICY "Admins can create animal photos"
  ON animal_photos FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Animal owners can update photos" ON animal_photos;
DROP POLICY IF EXISTS "Admins can update animal photos" ON animal_photos;
CREATE POLICY "Admins can update animal photos"
  ON animal_photos FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Animal owners can delete photos" ON animal_photos;
DROP POLICY IF EXISTS "Admins can delete animal photos" ON animal_photos;
CREATE POLICY "Admins can delete animal photos"
  ON animal_photos FOR DELETE
  TO authenticated
  USING (is_admin());

DROP POLICY IF EXISTS "Authenticated users can read active matching rules" ON matching_rules;
CREATE POLICY "Authenticated users can read active matching rules"
  ON matching_rules FOR SELECT
  TO authenticated
  USING (is_active = true OR is_admin());

DROP POLICY IF EXISTS "Admins can manage matching rules" ON matching_rules;
CREATE POLICY "Admins can manage matching rules"
  ON matching_rules FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Anyone can read animal photo objects" ON storage.objects;
CREATE POLICY "Anyone can read animal photo objects"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'animal-photos');

DROP POLICY IF EXISTS "Animal owners can upload animal photo objects" ON storage.objects;
DROP POLICY IF EXISTS "Admins can upload animal photo objects" ON storage.objects;
CREATE POLICY "Admins can upload animal photo objects"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'animal-photos'
    AND is_admin()
  );

DROP POLICY IF EXISTS "Animal owners can update animal photo objects" ON storage.objects;
DROP POLICY IF EXISTS "Admins can update animal photo objects" ON storage.objects;
CREATE POLICY "Admins can update animal photo objects"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'animal-photos'
    AND is_admin()
  )
  WITH CHECK (
    bucket_id = 'animal-photos'
    AND is_admin()
  );

DROP POLICY IF EXISTS "Animal owners can delete animal photo objects" ON storage.objects;
DROP POLICY IF EXISTS "Admins can delete animal photo objects" ON storage.objects;
CREATE POLICY "Admins can delete animal photo objects"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'animal-photos'
    AND is_admin()
  );

-- ============================================================
-- 004_restrict_tutors_rls.sql
-- ============================================================
ALTER TABLE tutors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tutors can read their own profile" ON tutors;
CREATE POLICY "Tutors can read their own profile"
  ON tutors FOR SELECT
  TO authenticated
  USING (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Tutors can create their own profile" ON tutors;
CREATE POLICY "Tutors can create their own profile"
  ON tutors FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Tutors can update their own profile" ON tutors;
CREATE POLICY "Tutors can update their own profile"
  ON tutors FOR UPDATE
  TO authenticated
  USING (auth.uid() = auth_user_id)
  WITH CHECK (auth.uid() = auth_user_id);

DROP POLICY IF EXISTS "Admins can delete tutors" ON tutors;

-- ============================================================
-- 005_custom_fields.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS custom_fields (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  entity_type VARCHAR(16) NOT NULL CHECK (entity_type IN ('tutor', 'animal')),
  field_key VARCHAR(64) NOT NULL CHECK (field_key ~ '^[a-z][a-z0-9_]*$'),
  label VARCHAR(120) NOT NULL,
  field_type VARCHAR(32) NOT NULL DEFAULT 'text' CHECK (field_type IN ('text', 'number', 'boolean', 'select', 'multiselect')),
  options JSONB,
  source_question_id VARCHAR(64) REFERENCES onboarding_questions(id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (entity_type, field_key)
);

CREATE INDEX IF NOT EXISTS custom_fields_entity_active_sort_idx
  ON custom_fields (entity_type, is_active, sort_order, label);

ALTER TABLE custom_fields ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read active custom fields" ON custom_fields;
CREATE POLICY "Authenticated users can read active custom fields"
  ON custom_fields FOR SELECT
  TO authenticated
  USING (is_active = true OR is_admin());

DROP POLICY IF EXISTS "Admins can manage custom fields" ON custom_fields;
CREATE POLICY "Admins can manage custom fields"
  ON custom_fields FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

INSERT INTO custom_fields (entity_type, field_key, label, field_type, options, source_question_id, is_active, sort_order)
VALUES
  ('tutor', 'pref_energia', 'Energia desejada', 'select', '["baixo","medio","alto"]'::jsonb, 'preferred_energy', true, 10),
  ('tutor', 'tem_criancas', 'Tem criancas', 'boolean', NULL, 'has_children', true, 20),
  ('tutor', 'tamanho_casa', 'Tamanho da casa', 'select', '["apartamento","casa_quintal_pequeno","casa_quintal_grande","pequeno","medio","grande"]'::jsonb, 'home_type', true, 30),
  ('tutor', 'tem_quintal', 'Tem quintal', 'boolean', NULL, NULL, true, 40),
  ('tutor', 'renda_mensal', 'Renda mensal', 'select', '["ate_1000","1000_3000","3000_6000","6000_acima"]'::jsonb, NULL, true, 50),
  ('tutor', 'disponibilidade_tempo', 'Disponibilidade de tempo', 'select', '["meio_periodo","integral"]'::jsonb, 'routine', true, 60),
  ('animal', 'nivel_energia', 'Nivel de energia', 'select', '["baixo","medio","alto"]'::jsonb, NULL, true, 10),
  ('animal', 'aceita_criancas', 'Aceita criancas', 'boolean', NULL, NULL, true, 20),
  ('animal', 'espaco_necessario', 'Espaco necessario', 'select', '["apartamento","casa_quintal_pequeno","casa_quintal_grande"]'::jsonb, NULL, true, 30),
  ('animal', 'tamanho', 'Tamanho', 'select', '["pequeno","medio","grande"]'::jsonb, NULL, true, 40),
  ('animal', 'requer_espaco', 'Espaco necessario', 'select', '["apartamento","casa_pequena","casa_grande"]'::jsonb, NULL, true, 50),
  ('animal', 'vacinado', 'Vacinado', 'boolean', NULL, NULL, true, 60)
ON CONFLICT (entity_type, field_key) DO UPDATE SET
  label = EXCLUDED.label,
  field_type = EXCLUDED.field_type,
  options = EXCLUDED.options,
  source_question_id = EXCLUDED.source_question_id,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

-- ============================================================
-- 006_tutor_interessados.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS tutor_interessados (
  tutor_id UUID NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
  animal_id UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
  data_registro TIMESTAMPTZ DEFAULT NOW(),
  uuid_registro UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  CONSTRAINT tutor_interessados_tutor_animal_key UNIQUE (tutor_id, animal_id)
);

CREATE INDEX IF NOT EXISTS tutor_interessados_tutor_id_idx
  ON tutor_interessados (tutor_id);

CREATE INDEX IF NOT EXISTS tutor_interessados_animal_id_idx
  ON tutor_interessados (animal_id);

ALTER TABLE tutor_interessados ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tutors can read their own interest records" ON tutor_interessados;
DROP POLICY IF EXISTS "Admins can read interest records" ON tutor_interessados;
CREATE POLICY "Admins can read interest records"
  ON tutor_interessados FOR SELECT
  TO authenticated
  USING (is_admin());

DROP POLICY IF EXISTS "Tutors can create their own interest records" ON tutor_interessados;
CREATE POLICY "Tutors can create their own interest records"
  ON tutor_interessados FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM tutors
      WHERE tutors.id = tutor_interessados.tutor_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- 007_calendar_events.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS calendar_events (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  tutor_id UUID REFERENCES tutors(id) ON DELETE SET NULL,
  animal_id UUID REFERENCES animals(id) ON DELETE SET NULL,
  interest_id UUID REFERENCES tutor_interessados(uuid_registro) ON DELETE SET NULL,
  title VARCHAR(160) NOT NULL,
  description TEXT,
  location VARCHAR(255),
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  provider VARCHAR(32) CHECK (provider IN ('google', 'microsoft')),
  external_event_id VARCHAR(255),
  external_event_url VARCHAR(2048),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_by UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CHECK (ends_at > starts_at)
);

CREATE INDEX IF NOT EXISTS calendar_events_starts_at_idx
  ON calendar_events (starts_at);

CREATE INDEX IF NOT EXISTS calendar_events_tutor_id_idx
  ON calendar_events (tutor_id);

CREATE INDEX IF NOT EXISTS calendar_events_animal_id_idx
  ON calendar_events (animal_id);

CREATE UNIQUE INDEX IF NOT EXISTS calendar_events_provider_external_idx
  ON calendar_events (provider, external_event_id)
  WHERE provider IS NOT NULL AND external_event_id IS NOT NULL;

ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage calendar events" ON calendar_events;
CREATE POLICY "Admins can manage calendar events"
  ON calendar_events FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- ============================================================
-- 008_service_configs.sql
-- ============================================================
-- Configuration for external services
CREATE TABLE service_configs (
  id VARCHAR(80) PRIMARY KEY,
  service_type VARCHAR(32) NOT NULL CHECK (service_type IN ('calendar')),
  provider VARCHAR(32) NOT NULL CHECK (provider IN ('google', 'microsoft')),
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN DEFAULT true,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policy for admins to manage service configs
ALTER TABLE service_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage service configs"
  ON service_configs FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- ============================================================
-- 009_interest_schedule_visibility.sql
-- ============================================================
ALTER TABLE calendar_events
  ADD COLUMN IF NOT EXISTS interest_id UUID REFERENCES tutor_interessados(uuid_registro) ON DELETE SET NULL;

ALTER TABLE calendar_events
  ADD COLUMN IF NOT EXISTS external_event_url VARCHAR(2048);

CREATE INDEX IF NOT EXISTS calendar_events_interest_id_idx
  ON calendar_events (interest_id);

DROP POLICY IF EXISTS "Tutors can read their own interest records" ON tutor_interessados;
CREATE POLICY "Tutors can read their own interest records"
  ON tutor_interessados FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM tutors
      WHERE tutors.id = tutor_interessados.tutor_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Tutors can read their own scheduled interest events" ON calendar_events;
CREATE POLICY "Tutors can read their own scheduled interest events"
  ON calendar_events FOR SELECT
  TO authenticated
  USING (
    status = 'scheduled'
    AND EXISTS (
      SELECT 1
      FROM tutor_interessados
      JOIN tutors ON tutors.id = tutor_interessados.tutor_id
      WHERE tutor_interessados.uuid_registro = calendar_events.interest_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- 010_custom_field_source_question.sql
-- ============================================================
ALTER TABLE custom_fields
  ADD COLUMN IF NOT EXISTS source_question_id VARCHAR(64) REFERENCES onboarding_questions(id) ON DELETE SET NULL;

UPDATE custom_fields
SET source_question_id = CASE field_key
  WHEN 'pref_energia' THEN 'preferred_energy'
  WHEN 'tem_criancas' THEN 'has_children'
  WHEN 'tamanho_casa' THEN 'home_type'
  WHEN 'disponibilidade_tempo' THEN 'routine'
  ELSE source_question_id
END
WHERE entity_type = 'tutor';

-- ============================================================
-- 011_ong_settings.sql
-- ============================================================
-- Public/contact settings for the ONG profile used by adoption flows.
CREATE TABLE IF NOT EXISTS ong_settings (
  id VARCHAR(32) PRIMARY KEY DEFAULT 'default' CHECK (id = 'default'),
  ong_name VARCHAR(160) NOT NULL DEFAULT 'ONG Matching Animal',
  contact_email VARCHAR(254),
  contact_phone VARCHAR(32),
  whatsapp_phone VARCHAR(32),
  website_url VARCHAR(2048),
  address_line VARCHAR(255),
  city VARCHAR(120),
  state VARCHAR(64),
  postal_code VARCHAR(20),
  social_links JSONB NOT NULL DEFAULT '{}'::jsonb,
  business_hours JSONB NOT NULL DEFAULT '{}'::jsonb,
  adoption_message_template TEXT DEFAULT 'Estou com interesse de adotar {nomeDoAnimal}. O link do interesse e {linkInteresse}.' || E'\n\n' || 'Observacoes:',
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (social_links IS NOT NULL AND jsonb_typeof(social_links) = 'object'),
  CHECK (business_hours IS NOT NULL AND jsonb_typeof(business_hours) = 'object'),
  CHECK (settings IS NOT NULL AND jsonb_typeof(settings) = 'object')
);

INSERT INTO ong_settings (id, ong_name, is_active)
VALUES ('default', 'ONG Matching Animal', true)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE ong_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read active ONG settings" ON ong_settings;
CREATE POLICY "Anyone can read active ONG settings"
  ON ong_settings FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

DROP POLICY IF EXISTS "Admins can manage ONG settings" ON ong_settings;
CREATE POLICY "Admins can manage ONG settings"
  ON ong_settings FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- ============================================================
-- 012_matching_rule_dealbreaker.sql
-- ============================================================
ALTER TABLE matching_rules
  ADD COLUMN IF NOT EXISTS is_dealbreaker BOOLEAN NOT NULL DEFAULT false;

CREATE OR REPLACE FUNCTION matching_value_rank(raw_value TEXT)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN raw_value IS NULL THEN 0
    WHEN raw_value ~ '^-?[0-9]+(\.[0-9]+)?$' THEN raw_value::NUMERIC
    WHEN raw_value IN ('baixo', 'apartamento') THEN 1
    WHEN raw_value IN ('medio', 'casa_sem_quintal', 'casa_quintal_pequeno', 'casa_pequena') THEN 2
    WHEN raw_value IN ('alto', 'casa_com_quintal', 'casa_quintal_grande', 'casa_grande') THEN 3
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION match_animals_for_tutor(target_tutor_id UUID, result_limit INT DEFAULT 10)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  tutor_fields JSONB;
BEGIN
  SELECT custom_fields INTO tutor_fields
  FROM tutors
  WHERE id = target_tutor_id;

  IF tutor_fields IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  WITH evaluated AS (
    SELECT
      animals.id AS animal_id,
      animals.name AS animal_name,
      rules.id AS rule_id,
      rules.rule_name,
      rules.weight,
      rules.is_dealbreaker,
      CASE rules.comparison_operator
        WHEN '=' THEN tutor_fields -> rules.tutor_field = animals.custom_fields -> rules.animal_field
        WHEN '!=' THEN tutor_fields -> rules.tutor_field <> animals.custom_fields -> rules.animal_field
        WHEN 'contains' THEN
          CASE
            WHEN jsonb_typeof(animals.custom_fields -> rules.animal_field) = 'array'
              THEN animals.custom_fields -> rules.animal_field ? (tutor_fields ->> rules.tutor_field)
            ELSE animals.custom_fields ->> rules.animal_field ILIKE '%' || (tutor_fields ->> rules.tutor_field) || '%'
          END
        WHEN '>=' THEN matching_value_rank(tutor_fields ->> rules.tutor_field) >= matching_value_rank(animals.custom_fields ->> rules.animal_field)
        WHEN '<=' THEN matching_value_rank(tutor_fields ->> rules.tutor_field) <= matching_value_rank(animals.custom_fields ->> rules.animal_field)
        ELSE false
      END AS matched
    FROM animals
    CROSS JOIN matching_rules rules
    WHERE rules.is_active = true
      AND tutor_fields ? rules.tutor_field
      AND animals.custom_fields ? rules.animal_field
  ),
  grouped AS (
    SELECT
      evaluated.animal_id,
      evaluated.animal_name,
      SUM(CASE WHEN evaluated.matched THEN evaluated.weight ELSE 0 END)::INT AS compatibility_score,
      BOOL_OR(evaluated.is_dealbreaker AND NOT evaluated.matched) AS disqualified,
      JSONB_AGG(evaluated.rule_id) FILTER (WHERE evaluated.matched) AS matched_rules,
      JSONB_AGG(JSONB_BUILD_OBJECT(
        'rule_id', evaluated.rule_id,
        'rule_name', evaluated.rule_name,
        'matched', evaluated.matched,
        'weight', evaluated.weight,
        'is_dealbreaker', evaluated.is_dealbreaker
      )) AS details
    FROM evaluated
    GROUP BY evaluated.animal_id, evaluated.animal_name
  )
  SELECT
    grouped.animal_id,
    grouped.animal_name,
    grouped.compatibility_score,
    COALESCE(grouped.matched_rules, '[]'::jsonb),
    COALESCE(grouped.details, '[]'::jsonb)
  FROM grouped
  WHERE grouped.disqualified = false
    AND grouped.compatibility_score > 0
  ORDER BY grouped.compatibility_score DESC, grouped.animal_name ASC
  LIMIT result_limit;
END;
$$;

-- ============================================================
-- 013_calendar_oauth_connections.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS calendar_oauth_connections (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  provider VARCHAR(32) NOT NULL CHECK (provider IN ('google', 'microsoft')),
  calendar_id VARCHAR(255) NOT NULL DEFAULT 'primary',
  account_email VARCHAR(254),
  tenant_id VARCHAR(128),
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  token_type VARCHAR(32) DEFAULT 'Bearer',
  scope TEXT,
  expires_at TIMESTAMPTZ,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS calendar_oauth_connections_provider_active_idx
  ON calendar_oauth_connections (provider, is_active, updated_at DESC);

ALTER TABLE calendar_oauth_connections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read calendar oauth connections" ON calendar_oauth_connections;
CREATE POLICY "Admins can read calendar oauth connections"
  ON calendar_oauth_connections FOR SELECT
  TO authenticated
  USING (is_admin());

DROP POLICY IF EXISTS "Admins can manage calendar oauth connections" ON calendar_oauth_connections;
CREATE POLICY "Admins can manage calendar oauth connections"
  ON calendar_oauth_connections FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- ============================================================
-- 014_calendar_sync_pgmq.sql
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgmq;

DO $$
BEGIN
  PERFORM pgmq.create('calendar_sync');
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
$$;

DO $$
BEGIN
  PERFORM pgmq.create('calendar_sync_failed');
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
$$;

CREATE OR REPLACE FUNCTION enqueue_calendar_sync_message()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  row_payload JSONB;
  sync_source TEXT;
  sync_operation TEXT;
BEGIN
  IF TG_OP = 'DELETE' THEN
    row_payload := to_jsonb(OLD);
    sync_source := OLD.metadata #>> '{calendar_sync,source}';
    sync_operation := 'delete';

    IF sync_source IN ('google', 'google_edge_function') THEN
      RETURN OLD;
    END IF;

    IF COALESCE(OLD.provider, 'google') = 'google' THEN
      PERFORM pgmq.send(
        'calendar_sync',
        jsonb_build_object(
          'provider', 'google',
          'operation', sync_operation,
          'calendar_event_id', OLD.id,
          'event_snapshot', row_payload,
          'enqueued_at', NOW()
        )
      );
    END IF;

    RETURN OLD;
  END IF;

  row_payload := to_jsonb(NEW);
  sync_source := NEW.metadata #>> '{calendar_sync,source}';
  sync_operation := 'upsert';

  IF sync_source IN ('google', 'google_edge_function') THEN
    RETURN NEW;
  END IF;

  IF COALESCE(NEW.provider, 'google') = 'google' THEN
    PERFORM pgmq.send(
      'calendar_sync',
      jsonb_build_object(
        'provider', 'google',
        'operation', sync_operation,
        'calendar_event_id', NEW.id,
        'event_snapshot', row_payload,
        'enqueued_at', NOW()
      )
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS calendar_events_enqueue_sync ON calendar_events;
CREATE TRIGGER calendar_events_enqueue_sync
AFTER INSERT OR UPDATE OR DELETE ON calendar_events
FOR EACH ROW EXECUTE FUNCTION enqueue_calendar_sync_message();

CREATE OR REPLACE FUNCTION read_calendar_sync_messages(
  visibility_timeout_seconds INTEGER DEFAULT 120,
  batch_size INTEGER DEFAULT 20
)
RETURNS TABLE (
  msg_id BIGINT,
  read_ct INTEGER,
  enqueued_at TIMESTAMPTZ,
  vt TIMESTAMPTZ,
  message JSONB
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pgmq
AS $$
  SELECT msg_id, read_ct, enqueued_at, vt, message
  FROM pgmq.read(
    'calendar_sync',
    GREATEST(1, LEAST(visibility_timeout_seconds, 3600)),
    GREATEST(1, LEAST(batch_size, 100))
  );
$$;

CREATE OR REPLACE FUNCTION archive_calendar_sync_message(message_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pgmq
AS $$
  SELECT pgmq.archive('calendar_sync', message_id);
$$;

CREATE OR REPLACE FUNCTION send_failed_calendar_sync_message(message JSONB)
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pgmq
AS $$
  SELECT * FROM pgmq.send('calendar_sync_failed', message);
$$;

REVOKE EXECUTE ON FUNCTION read_calendar_sync_messages(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION archive_calendar_sync_message(BIGINT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION send_failed_calendar_sync_message(JSONB) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION read_calendar_sync_messages(INTEGER, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION archive_calendar_sync_message(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION send_failed_calendar_sync_message(JSONB) TO service_role;

-- ============================================================
-- 015_register_missing_custom_field_labels.sql
-- ============================================================
-- Register labels for custom_fields keys already present in tutors.custom_fields
-- and animals.custom_fields.
--
-- This prevents admin UI fallbacks such as "Selecione o campo" when a stored
-- JSONB key exists in records but is missing from the custom_fields catalog.

INSERT INTO custom_fields (entity_type, field_key, label, field_type, options, source_question_id, is_active, sort_order)
VALUES
  -- Animal fields found in animals.custom_fields.
  ('animal', 'aceita_outros_animais', 'Aceita outros animais', 'boolean', NULL, NULL, true, 70),
  ('animal', 'castrado', 'Castrado', 'boolean', NULL, NULL, true, 80),
  ('animal', 'idade_meses', 'Idade em meses', 'number', NULL, NULL, true, 90),
  ('animal', 'peso_kg', 'Peso em kg', 'number', NULL, NULL, true, 100),
  ('animal', 'raca', 'Raca', 'text', NULL, NULL, true, 110),

  -- Raw onboarding answer keys stored for tutor traceability.
  ('tutor', 'has_children', 'Tem criancas', 'boolean', NULL, 'has_children', true, 70),
  ('tutor', 'home_type', 'Tipo de moradia', 'select', '["apartamento","casa_sem_quintal","casa_com_quintal"]'::jsonb, 'home_type', true, 80),
  ('tutor', 'preferred_energy', 'Energia preferida', 'select', '["baixo","medio","alto"]'::jsonb, 'preferred_energy', true, 90),
  ('tutor', 'preferences', 'Preferencias', 'multiselect', NULL, NULL, true, 100),
  ('tutor', 'routine', 'Rotina', 'select', '["meio_periodo","integral"]'::jsonb, 'routine', true, 110),
  ('tutor', 'notes', 'Observacoes', 'text', NULL, NULL, true, 120),

  -- Normalized keys generated from onboarding answers.
  ('tutor', 'preferencias', 'Preferencias', 'multiselect', NULL, NULL, true, 130),
  ('tutor', 'observacoes', 'Observacoes', 'text', NULL, NULL, true, 140),

  -- Technical profile state stored in custom_fields.
  ('tutor', 'onboarding_complete', 'Onboarding concluido', 'boolean', NULL, NULL, true, 999)
ON CONFLICT (entity_type, field_key) DO UPDATE SET
  label = EXCLUDED.label,
  field_type = EXCLUDED.field_type,
  options = EXCLUDED.options,
  source_question_id = EXCLUDED.source_question_id,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();

-- ============================================================
-- 016_document_custom_field_entity_type.sql
-- ============================================================
-- Document the custom_fields target entity metadata.
--
-- custom_fields.entity_type is the database field that indicates where a
-- custom field is used. Current valid values are:
-- - tutor: field is available in tutor custom_fields.
-- - animal: field is available in animal custom_fields.

COMMENT ON COLUMN custom_fields.entity_type IS
  'Defines where the custom field is used. Valid values: tutor, animal.';

-- ============================================================
-- 017_admin_audit_logs.sql
-- ============================================================
CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id uuid REFERENCES auth.users(id),
    action VARCHAR(32) NOT NULL,
    resource VARCHAR(80) NOT NULL,
    resource_id VARCHAR(128),
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.admin_audit_logs;
DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON public.admin_audit_logs;
DROP POLICY IF EXISTS "Admins can read admin audit logs" ON public.admin_audit_logs;
DROP POLICY IF EXISTS "Admins can insert admin audit logs" ON public.admin_audit_logs;

CREATE POLICY "Admins can read admin audit logs" ON public.admin_audit_logs
  FOR SELECT
  TO authenticated
  USING (public.is_admin(auth.uid()));

CREATE POLICY "Admins can insert admin audit logs" ON public.admin_audit_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin(auth.uid()) AND auth_user_id = auth.uid());

-- ============================================================
-- 018_calculate_match_score_rpc.sql
-- ============================================================
CREATE OR REPLACE FUNCTION calculate_match_score(
  target_tutor_id UUID,
  result_limit INT DEFAULT 10,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  tutor_fields JSONB;
  tutor_location geography(POINT);
BEGIN
  SELECT custom_fields, location INTO tutor_fields, tutor_location
  FROM tutors
  WHERE id = target_tutor_id;

  IF tutor_fields IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  WITH filtered_animals AS (
    SELECT animals.*
    FROM animals
    WHERE max_distance_km IS NULL
      OR tutor_location IS NULL
      OR animals.location IS NULL
      OR ST_DWithin(animals.location, tutor_location, max_distance_km * 1000)
  ),
  evaluated AS (
    SELECT
      filtered_animals.id AS animal_id,
      filtered_animals.name AS animal_name,
      rules.id AS rule_id,
      rules.rule_name,
      rules.weight,
      rules.is_dealbreaker,
      CASE rules.comparison_operator
        WHEN '=' THEN tutor_fields -> rules.tutor_field = filtered_animals.custom_fields -> rules.animal_field
        WHEN '!=' THEN tutor_fields -> rules.tutor_field <> filtered_animals.custom_fields -> rules.animal_field
        WHEN 'contains' THEN
          CASE
            WHEN jsonb_typeof(tutor_fields -> rules.tutor_field) = 'array'
              AND jsonb_typeof(filtered_animals.custom_fields -> rules.animal_field) = 'array'
              THEN EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(filtered_animals.custom_fields -> rules.animal_field) AS animal_item(value)
                WHERE tutor_fields -> rules.tutor_field ? animal_item.value
              )
            WHEN jsonb_typeof(tutor_fields -> rules.tutor_field) = 'array'
              THEN tutor_fields -> rules.tutor_field ? (filtered_animals.custom_fields ->> rules.animal_field)
            WHEN jsonb_typeof(filtered_animals.custom_fields -> rules.animal_field) = 'array'
              THEN EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(filtered_animals.custom_fields -> rules.animal_field) AS animal_item(value)
                WHERE tutor_fields ->> rules.tutor_field ILIKE '%' || animal_item.value || '%'
              )
            ELSE tutor_fields ->> rules.tutor_field ILIKE '%' || (filtered_animals.custom_fields ->> rules.animal_field) || '%'
          END
        WHEN '>=' THEN matching_value_rank(tutor_fields ->> rules.tutor_field) >= matching_value_rank(filtered_animals.custom_fields ->> rules.animal_field)
        WHEN '<=' THEN matching_value_rank(tutor_fields ->> rules.tutor_field) <= matching_value_rank(filtered_animals.custom_fields ->> rules.animal_field)
        ELSE false
      END AS matched
    FROM filtered_animals
    CROSS JOIN matching_rules rules
    WHERE rules.is_active = true
      AND tutor_fields ? rules.tutor_field
      AND filtered_animals.custom_fields ? rules.animal_field
  ),
  grouped AS (
    SELECT
      evaluated.animal_id,
      evaluated.animal_name,
      SUM(CASE WHEN evaluated.matched THEN evaluated.weight ELSE 0 END)::INT AS compatibility_score,
      BOOL_OR(evaluated.is_dealbreaker AND NOT evaluated.matched) AS disqualified,
      JSONB_AGG(evaluated.rule_id) FILTER (WHERE evaluated.matched) AS matched_rules,
      JSONB_AGG(JSONB_BUILD_OBJECT(
        'rule_id', evaluated.rule_id,
        'rule_name', evaluated.rule_name,
        'matched', evaluated.matched,
        'weight', evaluated.weight,
        'is_dealbreaker', evaluated.is_dealbreaker
      )) AS details
    FROM evaluated
    GROUP BY evaluated.animal_id, evaluated.animal_name
  )
  SELECT
    grouped.animal_id,
    grouped.animal_name,
    grouped.compatibility_score,
    COALESCE(grouped.matched_rules, '[]'::jsonb),
    COALESCE(grouped.details, '[]'::jsonb)
  FROM grouped
  WHERE grouped.disqualified = false
    AND grouped.compatibility_score > 0
  ORDER BY grouped.compatibility_score DESC, grouped.animal_name ASC
  LIMIT result_limit;
END;
$$;

CREATE OR REPLACE FUNCTION count_match_candidates_for_tutor(
  target_tutor_id UUID,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS INT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  tutor_location geography(POINT);
  total_candidates INT;
BEGIN
  SELECT location INTO tutor_location
  FROM tutors
  WHERE id = target_tutor_id;

  IF NOT FOUND THEN
    RETURN 0;
  END IF;

  SELECT COUNT(*)::INT INTO total_candidates
  FROM animals
  WHERE max_distance_km IS NULL
    OR tutor_location IS NULL
    OR animals.location IS NULL
    OR ST_DWithin(animals.location, tutor_location, max_distance_km * 1000);

  RETURN total_candidates;
END;
$$;

CREATE OR REPLACE FUNCTION match_animals_for_tutor(
  target_tutor_id UUID,
  result_limit INT DEFAULT 10,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM calculate_match_score(target_tutor_id, result_limit, max_distance_km);
$$;

-- ============================================================
-- 019_add_performance_indexes.sql
-- ============================================================
DROP INDEX IF EXISTS public.tutors_auth_user_id_idx;
DROP INDEX IF EXISTS public.admin_users_auth_user_id_idx;

CREATE INDEX IF NOT EXISTS idx_animals_owner_id
ON public.animals (owner_id);

CREATE INDEX IF NOT EXISTS idx_animals_location_gist
ON public.animals USING gist (location);

-- ============================================================
-- 019_matching_cache_pg_cron.sql
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE TABLE IF NOT EXISTS tutor_animal_matches (
  tutor_id UUID NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
  animal_id UUID NOT NULL REFERENCES animals(id) ON DELETE CASCADE,
  compatibility_score INT NOT NULL,
  matched_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  details JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (tutor_id, animal_id)
);

CREATE INDEX IF NOT EXISTS idx_tutor_matches_score
  ON tutor_animal_matches (tutor_id, compatibility_score DESC);

CREATE OR REPLACE FUNCTION compute_tutor_animal_matches(target_tutor_id UUID)
RETURNS TABLE (
  tutor_id UUID,
  animal_id UUID,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  WITH tutor_profile AS (
    SELECT tutors.id, tutors.custom_fields
    FROM tutors
    WHERE tutors.id = target_tutor_id
  ),
  evaluated AS (
    SELECT
      tutor_profile.id AS tutor_id,
      animals.id AS animal_id,
      rules.id AS rule_id,
      rules.rule_name,
      rules.weight,
      rules.is_dealbreaker,
      CASE rules.comparison_operator
        WHEN '=' THEN tutor_profile.custom_fields -> rules.tutor_field = animals.custom_fields -> rules.animal_field
        WHEN '!=' THEN tutor_profile.custom_fields -> rules.tutor_field <> animals.custom_fields -> rules.animal_field
        WHEN 'contains' THEN
          CASE
            WHEN jsonb_typeof(tutor_profile.custom_fields -> rules.tutor_field) = 'array'
              AND jsonb_typeof(animals.custom_fields -> rules.animal_field) = 'array'
              THEN EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(animals.custom_fields -> rules.animal_field) AS animal_item(value)
                WHERE tutor_profile.custom_fields -> rules.tutor_field ? animal_item.value
              )
            WHEN jsonb_typeof(tutor_profile.custom_fields -> rules.tutor_field) = 'array'
              THEN tutor_profile.custom_fields -> rules.tutor_field ? (animals.custom_fields ->> rules.animal_field)
            WHEN jsonb_typeof(animals.custom_fields -> rules.animal_field) = 'array'
              THEN EXISTS (
                SELECT 1
                FROM jsonb_array_elements_text(animals.custom_fields -> rules.animal_field) AS animal_item(value)
                WHERE tutor_profile.custom_fields ->> rules.tutor_field ILIKE '%' || animal_item.value || '%'
              )
            ELSE tutor_profile.custom_fields ->> rules.tutor_field ILIKE '%' || (animals.custom_fields ->> rules.animal_field) || '%'
          END
        WHEN '>=' THEN matching_value_rank(tutor_profile.custom_fields ->> rules.tutor_field) >= matching_value_rank(animals.custom_fields ->> rules.animal_field)
        WHEN '<=' THEN matching_value_rank(tutor_profile.custom_fields ->> rules.tutor_field) <= matching_value_rank(animals.custom_fields ->> rules.animal_field)
        ELSE false
      END AS matched
    FROM tutor_profile
    JOIN animals ON true
    CROSS JOIN matching_rules rules
    WHERE rules.is_active = true
      AND tutor_profile.custom_fields ? rules.tutor_field
      AND animals.custom_fields ? rules.animal_field
  ),
  grouped AS (
    SELECT
      evaluated.tutor_id,
      evaluated.animal_id,
      SUM(CASE WHEN evaluated.matched THEN evaluated.weight ELSE 0 END)::INT AS compatibility_score,
      BOOL_OR(evaluated.is_dealbreaker AND NOT evaluated.matched) AS disqualified,
      JSONB_AGG(evaluated.rule_id) FILTER (WHERE evaluated.matched) AS matched_rules,
      JSONB_AGG(JSONB_BUILD_OBJECT(
        'rule_id', evaluated.rule_id,
        'rule_name', evaluated.rule_name,
        'matched', evaluated.matched,
        'weight', evaluated.weight,
        'is_dealbreaker', evaluated.is_dealbreaker
      )) AS details
    FROM evaluated
    GROUP BY evaluated.tutor_id, evaluated.animal_id
  )
  SELECT
    grouped.tutor_id,
    grouped.animal_id,
    grouped.compatibility_score,
    COALESCE(grouped.matched_rules, '[]'::jsonb),
    COALESCE(grouped.details, '[]'::jsonb)
  FROM grouped
  WHERE grouped.disqualified = false
    AND grouped.compatibility_score > 0;
$$;

CREATE OR REPLACE FUNCTION refresh_tutor_animal_matches(target_tutor_id UUID)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  refreshed_rows INT := 0;
BEGIN
  DELETE FROM tutor_animal_matches
  WHERE tutor_id = target_tutor_id;

  INSERT INTO tutor_animal_matches (
    tutor_id,
    animal_id,
    compatibility_score,
    matched_rules,
    details,
    updated_at
  )
  SELECT
    computed.tutor_id,
    computed.animal_id,
    computed.compatibility_score,
    computed.matched_rules,
    computed.details,
    NOW()
  FROM compute_tutor_animal_matches(target_tutor_id) AS computed;

  GET DIAGNOSTICS refreshed_rows = ROW_COUNT;
  RETURN refreshed_rows;
END;
$$;

CREATE OR REPLACE FUNCTION refresh_all_tutor_animal_matches()
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  tutor_record RECORD;
  refreshed_total INT := 0;
BEGIN
  FOR tutor_record IN
    SELECT tutors.id
    FROM tutors
  LOOP
    refreshed_total := refreshed_total + refresh_tutor_animal_matches(tutor_record.id);
  END LOOP;

  RETURN refreshed_total;
END;
$$;

CREATE OR REPLACE FUNCTION match_animals_for_tutor(
  target_tutor_id UUID,
  result_limit INT DEFAULT 10,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  WITH tutor_profile AS (
    SELECT tutors.id, tutors.location
    FROM tutors
    WHERE tutors.id = target_tutor_id
  )
  SELECT
    cache.animal_id,
    animals.name AS animal_name,
    cache.compatibility_score,
    cache.matched_rules,
    cache.details
  FROM tutor_animal_matches AS cache
  JOIN tutor_profile
    ON tutor_profile.id = cache.tutor_id
  JOIN animals
    ON animals.id = cache.animal_id
  WHERE cache.tutor_id = target_tutor_id
    AND (
      max_distance_km IS NULL
      OR tutor_profile.location IS NULL
      OR animals.location IS NULL
      OR ST_DWithin(animals.location, tutor_profile.location, max_distance_km * 1000)
    )
  ORDER BY cache.compatibility_score DESC, animals.name ASC
  LIMIT result_limit;
$$;

CREATE OR REPLACE FUNCTION calculate_match_score(
  target_tutor_id UUID,
  result_limit INT DEFAULT 10,
  max_distance_km NUMERIC DEFAULT 50
)
RETURNS TABLE (
  animal_id UUID,
  animal_name TEXT,
  compatibility_score INT,
  matched_rules JSONB,
  details JSONB
)
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM match_animals_for_tutor(target_tutor_id, result_limit, max_distance_km);
$$;

ALTER TABLE tutor_animal_matches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tutors can read their own cached matches" ON tutor_animal_matches;
CREATE POLICY "Tutors can read their own cached matches"
  ON tutor_animal_matches FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM tutors
      WHERE tutors.id = tutor_animal_matches.tutor_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Admins can manage cached matches" ON tutor_animal_matches;
CREATE POLICY "Admins can manage cached matches"
  ON tutor_animal_matches FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

SELECT refresh_all_tutor_animal_matches();

DO $$
DECLARE
  existing_job_id BIGINT;
BEGIN
  SELECT cron.job.jobid
  INTO existing_job_id
  FROM cron.job
  WHERE cron.job.jobname = 'refresh-tutor-animal-matches'
  LIMIT 1;

  IF existing_job_id IS NOT NULL THEN
    PERFORM cron.unschedule(existing_job_id);
  END IF;

  PERFORM cron.schedule(
    'refresh-tutor-animal-matches',
    '*/15 * * * *',
    $cron$SELECT refresh_all_tutor_animal_matches();$cron$
  );
END;
$$;

-- ============================================================
-- 020_account_onboarding_timestamps.sql
-- ============================================================
ALTER TABLE tutors
  ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;

ALTER TABLE onboarding_questions
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

UPDATE onboarding_questions
SET updated_at = COALESCE(updated_at, created_at, NOW())
WHERE updated_at IS NULL;

CREATE INDEX IF NOT EXISTS onboarding_questions_active_updated_at_idx
  ON onboarding_questions (is_active, updated_at DESC);

-- ============================================================
-- 021_constrain_short_text_columns.sql
-- ============================================================
-- Bound short, structured text columns while keeping free-form content as TEXT.
-- PostgreSQL stores TEXT and VARCHAR similarly, so these limits are mainly data-quality
-- constraints for IDs, labels, statuses, URLs and contact fields.

ALTER TABLE IF EXISTS custom_fields
  DROP CONSTRAINT IF EXISTS custom_fields_source_question_id_fkey;

DROP POLICY IF EXISTS "Tutors can read their own scheduled interest events" ON calendar_events;

ALTER TABLE IF EXISTS tutors
  ALTER COLUMN name TYPE VARCHAR(120);

ALTER TABLE IF EXISTS admin_users
  ALTER COLUMN email TYPE VARCHAR(254);

ALTER TABLE IF EXISTS animals
  ALTER COLUMN name TYPE VARCHAR(120),
  ALTER COLUMN species TYPE VARCHAR(64);

ALTER TABLE IF EXISTS animal_photos
  ALTER COLUMN bucket_id TYPE VARCHAR(63),
  ALTER COLUMN storage_path TYPE VARCHAR(1024),
  ALTER COLUMN public_url TYPE VARCHAR(2048),
  ALTER COLUMN content_type TYPE VARCHAR(32);

ALTER TABLE IF EXISTS calendar_events
  ALTER COLUMN title TYPE VARCHAR(160),
  ALTER COLUMN location TYPE VARCHAR(255),
  ALTER COLUMN status TYPE VARCHAR(24),
  ALTER COLUMN provider TYPE VARCHAR(32),
  ALTER COLUMN external_event_id TYPE VARCHAR(255),
  ALTER COLUMN external_event_url TYPE VARCHAR(2048);

ALTER TABLE IF EXISTS ong_settings
  ALTER COLUMN id TYPE VARCHAR(32),
  ALTER COLUMN ong_name TYPE VARCHAR(160),
  ALTER COLUMN contact_email TYPE VARCHAR(254),
  ALTER COLUMN contact_phone TYPE VARCHAR(32),
  ALTER COLUMN whatsapp_phone TYPE VARCHAR(32),
  ALTER COLUMN website_url TYPE VARCHAR(2048),
  ALTER COLUMN address_line TYPE VARCHAR(255),
  ALTER COLUMN city TYPE VARCHAR(120),
  ALTER COLUMN state TYPE VARCHAR(64),
  ALTER COLUMN postal_code TYPE VARCHAR(20);

ALTER TABLE IF EXISTS onboarding_questions
  ALTER COLUMN id TYPE VARCHAR(64),
  ALTER COLUMN label TYPE VARCHAR(180),
  ALTER COLUMN placeholder TYPE VARCHAR(255),
  ALTER COLUMN type TYPE VARCHAR(32);

ALTER TABLE IF EXISTS custom_fields
  ALTER COLUMN entity_type TYPE VARCHAR(16),
  ALTER COLUMN field_key TYPE VARCHAR(64),
  ALTER COLUMN label TYPE VARCHAR(120),
  ALTER COLUMN field_type TYPE VARCHAR(32),
  ALTER COLUMN source_question_id TYPE VARCHAR(64);

ALTER TABLE IF EXISTS custom_fields
  ADD CONSTRAINT custom_fields_source_question_id_fkey
  FOREIGN KEY (source_question_id) REFERENCES onboarding_questions(id) ON DELETE SET NULL;

ALTER TABLE IF EXISTS matching_rules
  ALTER COLUMN rule_name TYPE VARCHAR(120),
  ALTER COLUMN tutor_field TYPE VARCHAR(64),
  ALTER COLUMN animal_field TYPE VARCHAR(64),
  ALTER COLUMN comparison_operator TYPE VARCHAR(16);

ALTER TABLE IF EXISTS service_configs
  ALTER COLUMN id TYPE VARCHAR(80),
  ALTER COLUMN service_type TYPE VARCHAR(32),
  ALTER COLUMN provider TYPE VARCHAR(32);

ALTER TABLE IF EXISTS calendar_oauth_connections
  ALTER COLUMN provider TYPE VARCHAR(32),
  ALTER COLUMN calendar_id TYPE VARCHAR(255),
  ALTER COLUMN account_email TYPE VARCHAR(254),
  ALTER COLUMN tenant_id TYPE VARCHAR(128),
  ALTER COLUMN token_type TYPE VARCHAR(32);

ALTER TABLE IF EXISTS public.admin_audit_logs
  ALTER COLUMN action TYPE VARCHAR(32),
  ALTER COLUMN resource TYPE VARCHAR(80),
  ALTER COLUMN resource_id TYPE VARCHAR(128);

CREATE POLICY "Tutors can read their own scheduled interest events"
  ON calendar_events FOR SELECT
  TO authenticated
  USING (
    status = 'scheduled'
    AND EXISTS (
      SELECT 1
      FROM tutor_interessados
      JOIN tutors ON tutors.id = tutor_interessados.tutor_id
      WHERE tutor_interessados.uuid_registro = calendar_events.interest_id
        AND tutors.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- 022_unique_tutor_animal_interests.sql
-- ============================================================
WITH ranked_interests AS (
  SELECT
    uuid_registro,
    tutor_id,
    animal_id,
    FIRST_VALUE(uuid_registro) OVER (
      PARTITION BY tutor_id, animal_id
      ORDER BY data_registro ASC NULLS LAST, uuid_registro ASC
    ) AS keep_uuid,
    ROW_NUMBER() OVER (
      PARTITION BY tutor_id, animal_id
      ORDER BY data_registro ASC NULLS LAST, uuid_registro ASC
    ) AS duplicate_rank
  FROM public.tutor_interessados
),
duplicate_interests AS (
  SELECT uuid_registro, keep_uuid
  FROM ranked_interests
  WHERE duplicate_rank > 1
)
UPDATE public.calendar_events
SET interest_id = duplicate_interests.keep_uuid
FROM duplicate_interests
WHERE public.calendar_events.interest_id = duplicate_interests.uuid_registro
  AND public.calendar_events.interest_id <> duplicate_interests.keep_uuid;

WITH ranked_interests AS (
  SELECT
    uuid_registro,
    tutor_id,
    animal_id,
    ROW_NUMBER() OVER (
      PARTITION BY tutor_id, animal_id
      ORDER BY data_registro ASC NULLS LAST, uuid_registro ASC
    ) AS duplicate_rank
  FROM public.tutor_interessados
)
DELETE FROM public.tutor_interessados
USING ranked_interests
WHERE public.tutor_interessados.uuid_registro = ranked_interests.uuid_registro
  AND ranked_interests.duplicate_rank > 1;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tutor_interessados_tutor_animal_key'
      AND conrelid = 'public.tutor_interessados'::regclass
  ) THEN
    ALTER TABLE public.tutor_interessados
      ADD CONSTRAINT tutor_interessados_tutor_animal_key UNIQUE (tutor_id, animal_id);
  END IF;
END $$;
