import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const dbDir = resolve(scriptDir, "..");
const migrationsDir = join(dbDir, "migrations");
const schemaPath = join(dbDir, "schema.sql");
const outputPath = process.argv[2]
  ? resolve(process.argv[2])
  : join(dbDir, "all_migrations.sql");

const migrationFiles = readdirSync(migrationsDir)
  .filter((file) => file.endsWith(".sql"))
  .sort((left, right) => left.localeCompare(right, "en"));

const header = [
  "-- Combined migrations for ONG Matching Animal.",
  "-- Generated by src/backend/db/scripts/build_combined_migrations.mjs.",
  "-- Includes the baseline schema followed by migrations in filename order.",
  "-- Review before running in production. Run in a clean database or after",
  "-- src/backend/db/scripts/drop_system_tables.sql when you intentionally want a rebuild.",
  "",
].join("\n");

const baselineSchema = [
  `-- ============================================================`,
  `-- schema.sql`,
  `-- ============================================================`,
  readFileSync(schemaPath, "utf8").trim(),
  "",
].join("\n");

const body = migrationFiles.map((file) => {
  const content = readFileSync(join(migrationsDir, file), "utf8").trim();
  return [
    `-- ============================================================`,
    `-- ${file}`,
    `-- ============================================================`,
    content,
    "",
  ].join("\n");
}).join("\n");

writeFileSync(outputPath, `${header}${baselineSchema}\n${body}`, "utf8");
console.log(`Combined schema.sql and ${migrationFiles.length} migrations into ${outputPath}`);
